### ISSUE TITLE
Удаление пользователя из списка админов

### ISSUE THREAD

**Issue by MaksInsce** [Studio-Yandex-Practicum/telestat_bot_team_3#20]

**Comment by MaksInsce** [comment]
## Добавить боту возможонсть удалять пользователя из списка администраторов
## В продолжении создания crud функций нужно реализовать patch метод, посредством подключения через session к бд, изменять значение поля is_admin на False, чтобы ограничить пользователя в использовании бота
## Код функции расположить в одном файле crud/base.py

**Comment by dk-1983** [comment]
Макс, так как пользователей нужно не удалять а переводить в статус is_active=False, то удаление пользователя в этой концепции ни что иное как надстройка в add_users(username, users=None, is_superuser=False, in_active=True). Поэтому это не метод удаления, а всего лишь ещё один аргумент метода add_users
