### ISSUE TITLE
Запустить логику работы бота

### ISSUE THREAD

**Issue by MaksInsce** [Studio-Yandex-Practicum/telestat_bot_team_3#42]

**Comment by MaksInsce** [comment]
## Добавить весь имющийся функционал в файл
## Воспроизвести работу бота с помощью кнопок. Настроить порядок вызова функции. Предусмотреть и перехватить возможные ошибки на каждом этапе функции. Также добавить отправку уведомлений пользователю о работе бота после каждого вызова действия
## Работу проделать в файле logic.py

**Comment by orbikadm** [comment]
Логика функций перенесена в файл logic.py
добавлена проверка на админа перед запуском функций

Доделать:
перехват и обработка ошибок

**Comment by orbikadm** [comment]
> Логика функций перенесена в файл logic.py добавлена проверка на админа перед запуском функций
> 
> Доделать: перехват и обработка ошибок

Сделана проверка входящей команды для добавления/удаления админа
Прописаны сообщения для пользователя с подсказками

Доделать: перехват и обработка ошибок
